language: node_js
node_js:
- 0.11.14
before_install:
- npm install -g npm@latest
notifications:
  email: false
script: npm run-script deploy
env:
  global:
  - GH_REF: github.com/shark-js/shark-js.github.io.git
  - secure: gYTKr7GAnvhsfryhCeCrD7+Bs+nxySRzaEhToxaKYhgeikInTea1kW8VyuXIKmlMm64RPLiIa/N2lHzGS0oteVYxQ2iNQ3Mh1M7yqJxqsbXP2c3cNZZ+uqODCO0UCYb/VAABNJCkbHh0HRo0jyQvdVWJXCv90wcUvs2h5YevcyE=
